### ISSUE TITLE
Uses outdated version of sundown

### ISSUE THREAD

**Issue by Malsententia** [chobie/php-sundown#1]
The latest version or two of sundown have added a few features, and parse a few things in a slightly different manner. The changes are significant enough that one cannot simply drop in the new sundown and recompile php-sundown.

**Comment by chobie** [comment]
thank you for spotting a issue. i've forgotten to integrate it on development branch.
there were some issues on that. let me check again.

**Comment by chobie** [comment]
hey, php-sundown is able to use latest sundown library and fix several issues. please check it if you have a chance.

https://github.com/chobie/php-sundown/blob/development/README.md

i'll stabilize it and propose to PECL near the future.
