### ISSUE TITLE
New lines interpretation

### ISSUE THREAD

**Issue by Genokilller** [chobie/php-sundown#15]
Hi,

I'd detect some other bugs for new line interpretation:

``` html
Original:

**test a écrit:**
> look 
> at
> 
> this
> 
> 
> Exemple !
```

Render:
**test a écrit:**

> look 
> at
> this
> Exemple !

Do you see the fail ?

New lines are droped in the quotation.
Maybe a fail of the "lax_html_blocks" extension ?

This is so problematic and disturb users ^^

Thanks for all !

**Comment by ikwattro** [comment]
@Genokilller By looking at the [markdown syntax](http://daringfireball.net/projects/markdown/syntax#blockquote) and the tests I've made for blockquotes https://github.com/kwattro/KwattroMarkdownBundle/blob/master/Tests/Markdown/Syntax/BlockquotesTest.php#L51 I think the behavior here is normal.
When adding an empty line inside a blockquote it will close and reopen the paragraph tag.

**Comment by chobie** [comment]
I agree @kwattro's comment. I've checked markdown-extra and redcarpet behavior. It same as php-sundown.

Original:

**test a écrit:**

> look 
> at
> 
> this
> 
> Exemple !

Then what is the difference between github and other markdown outputs: 
Probably github uses custom render method like this.

https://gist.github.com/2435868

this render will output
http://gyazo.com/e32e85a7b948a9d0a27cc695e67d1b4d

**Comment by Genokilller** [comment]
Ok, thanks for the doc.

Can't we addopt or develop an option to enable this output ?
This could be a great evolution in the direction of the github flavored markdown. :)

Do you think that it's logical to add correctly new lines in text and not in quotes ?

Sundown hasn't develop this extension since the last months ?

Thanks a lot for all your work !

**Comment by ikwattro** [comment]
[github](http://github.github.com/github-flavored-markdown/) treats line breaks as new lines, code here : https://github.com/tanoku/redcarpet/blob/master/ext/redcarpet/html.c#L208 .

Maybe we can ask @chobie to add some option in the xhml renderer, or if he don't want to add it to the original renderers of his code, to create for us a special renderer that will do it ? We will be very thankful. But I would wait that we complete our test suite so he can do it with detected issues.

What do you think @Genokilller @chobie ?

**Comment by Genokilller** [comment]
HI,

I thinks that's a great idea. We add to perform the best "markdown" render. 
So our aim should be to add some features like github flavored markdown is doing in redcarpet.

Can we start a new branch for this work ? 

@kwattro That's sure, unit tests have to be completed asap.

**Comment by chobie** [comment]
@kwattro Thanks spotting redcarpet code. I realized I completely forget `hard_wrap` render option.

available render options (quoted from redcarpet README).

```
:filter_html - do not allow any user-inputted HTML in the output

:no_images - do not generate any `<img>` tags

:no_links - do not generate any `<a>` tags

:no_styles - do not generate any `<style>` tags

:safe_links_only - only generate links for protocols which are considered safe

:with_toc_data - add HTML anchors to each header in the output HTML,
    to allow linking to each section.

:hard_wrap - insert HTML `<br>` tags inside on paragraphs where the origin
    Markdown document had newlines (by default, Markdown ignores these
    newlines).

:xhtml - output XHTML-conformant tags. This option is always enabled in the
    `Render::XHTML` renderer.
```

```
<?php
$render = new Sundown\Render\HTML(array("hard_wrap"=>true));
$sd = new Sundown\Markdown($render);
```

It doesn't need to create a custom render in this case :sweat:

By the way. What kind of options do you guys want to add? I'll agree to add it If it can implement in php-sundown.

**Comment by Genokilller** [comment]
Hi guys !

After some research, i found the solution for my quotes !

This is only a css problem. To have the same rendering of github, you have to add a margin on some html elements.

``` css
.markdown-body p, .markdown-body blockquote, .markdown-body ul, .markdown-body ol, .markdown-body dl, .markdown-body li, .markdown-body table, .markdown-body pre {
    margin: 15px 0;
}
```

This should be documented somewhere ^^

Thanks for all, i'll contact you if i need some other features.

**Comment by chobie** [comment]
Your welcome :smile:
