### ISSUE TITLE
space_after_headers

### ISSUE THREAD

**Issue by ikwattro** [chobie/php-sundown#16]
Hi @chobie : sorry to make your days hard but your sundown implementation aims to be used on high traffic website so we have to detect before production any possible issues.

I've discovered with this test : https://github.com/kwattro/KwattroMarkdownBundle/blob/master/Tests/Markdown/Syntax/HeadersTest.php#L95 that a header without space is still rendered as a header, space_after_headers is set to true in my config.

Can you take a look plz ? Thanls

**Comment by chobie** [comment]
@kwattro Thank you so much:heart:

it would be better to use vendors/.composer/autoload.php instead of UniversalClassloader. and add  "twig/twig" dependency like this.

https://gist.github.com/2435371

**Comment by igorw** [comment]
It's now just `vendor/autoload.php`.

**Comment by ikwattro** [comment]
I'll update it, Thanks @igorw and @chobie .
