### ISSUE TITLE
Force installation prefix doesn't work

### ISSUE THREAD

**Issue by toben** [chobie/php-sundown#17]
Hello !
I wanted to make a deb package of your library but I got some issues. I wanted to force the prefix to /tmp/sundown. 
So, I put it in the RakeFile :
desc "compile php-sundown"
task :compile => ['sundown/src/markdown.h'] do
    sh "phpize"
    sh "./configure --prefix=/tmp/sundown/"
    sh "make"
end

But, the installation still need the root rights and install nothing in this directory.
How can I fix that ? Do you have an idea ?

P.S: Sorry, if my english isn't that good.

**Comment by chobie** [comment]
I'm not sure to make a debian package. but, you can make your deb package with following step.

```
sudo aptitude install dh-make-php
export DEBEMAIL="your email"
export DEBFULLNAME="Your Name"
# downloading package file is easiest way.
pecl download sundown-beta
mkdir deb
mv sundown-0.3.3.tar.gz deb
cd deb
dh-make-pecl sundown-0.3.3.tgz 
cd sundown-0.3.3
debuild -uc -us
```

Basically, phpize depends on you php system. probably it try to install under `/usr/local` directory in your case.

**Comment by toben** [comment]
Thanks a lot ! I didn't know pecl. There was just some mistake in your script (bad directory name), I fixed it :
sudo aptitude install dh-make-php # or sudo apt-get install dh-make-php
export DEBEMAIL="Your email"
export DEBFULLNAME="Your name"
pecl download sundown-beta
mkdir deb
mv sundown-0.3.3.tgz deb
cd deb
dh-make-pecl sundown-0.3.3.tgz --depends xsltproc
cd php-sundown-0.3.3
cd sundown-0.3.3
debuild -uc -us

Thanks again !
