### ISSUE TITLE
Autolink is broken for emails

### ISSUE THREAD

**Issue by stof** [chobie/php-sundown#19]
Links generated for emails are wrong. The `mailto:` part is missing. I'm not sure if the issue is in php-sundown or in sundown itself.

Testcase to reproduce it:

``` php
<?php

$sundown = new Sundown\Markdown(
    new Sundown\Render\HTML(array('hard_wrap' => true)),
    array(
        'no_intra_emphasis' =>true,
        'tables' => true,
        'fenced_code_blocks' => true,
        'autolink' => true,
        'strikethrough' => true,
        'lax_html_blocks' => true,
    )
);

var_dump($sundown->render(
    <<<MARKDOWN
http://foo.bar/
test@example.com
MARKDOWN
));
```

Expected output:

``` html
<p><a href="http://foo.bar/">http://foo.bar/</a><br>
<a href="mailto:test@example.com">test@example.com</a></p>
```

Actual output:

``` html
<p><a href="http://foo.bar/">http://foo.bar/</a><br>
<a href="test@example.com">test@example.com</a></p>
```

**Comment by chobie** [comment]
Thank you spotting issue. I've just fixed this issue.

probably I forget some same issues. let me take a look at it.

**Comment by stof** [comment]
just to be able to tell my boss our bug will be fixed, when do you expect to release the next version with this bugfix ?

**Comment by chobie** [comment]
I've just release 0.3.5. now, you can use latest php-sudown with following command: `pecl install sundown-0.3.5`
