### ISSUE TITLE
Consider using Hoedown

### ISSUE THREAD

**Issue by devinus** [chobie/php-sundown#33]
I have revived Sundown into an improved library called Hoedown!

https://github.com/hoedown/hoedown

Here, I merged long languishing pull requests from Sundown, merged almost every improvement from Redcarpet, merged improvements from Rinku and Houdini, greatly improved and standardized the API, and fixed many potential bugs.

Full list of changes: https://github.com/hoedown/hoedown/compare/vmg:master...master

Sundown had a rich [collection of bindings](https://github.com/vmg/sundown#bindings) and it would truly be a shame if we couldn't all benefit from a single library in the future.

**Comment by chobie** [comment]
@devinus Thank you maintain Hoedown!

I'm going to move Hoedown. maybe it takes 2 or 3 weeks.I'll edit your wiki when I finished my task.

**Comment by devinus** [comment]
@chobie Good to hear! If you need any help navigating the API changes, let me know. I plan to write a doc for binding authors, but it's actually quite simple. E.g. `bufrelease` becomes `hoedown_buffer_free`, everything is now prefixed with `hoedown_*`, etc.

**Comment by dedalozzo** [comment]
Any news about the porting to Hoedown? Sundown has been abandoned and it's bugged.

The following markdown text for example it's not properly converted: 

```
The history of [Phil Fish](https://en.wikipedia.org/wiki/Phil_Fish_(video_game_developer)).
```

This is the output. As you can see there is one more parenthesis:

The history of [Phil Fish](https://en.wikipedia.org/wiki/Phil_Fish_%28video_game_developer%29))

**Comment by chobie** [comment]
current status is work in progress. (https://github.com/chobie/php-sundown/tree/hoedown)

I found compatibility issue (it already fixed) when I was porting it. I'll take look into this in weekend.

**Comment by chobie** [comment]
I'm re-considering about this topic. hoedown improves their api but it's not compatible with sundown.
I've spend several days but porting hasn't finished yet. this might tough work.

btw, PECL Sundown should correspond to redcarpet as I wanted to use that with PHP at that time.
hoedown has little bit different design concept. so new PHP extension would be better I think.

hoedown is developing new api (v3) right now. I'll watch hoedown development several weeks and make a decision about porting it whether not.

**Comment by devinus** [comment]
@chobie We're here to help you if you need us. The big v3 API changes have already landed, and I don't anticipate any more big changes coming. We also have started a migration guide: https://github.com/hoedown/hoedown/wiki/Migration-Guide

@jmendeth

**Comment by mildsunrise** [comment]
@devinus is right. We haven't released v3 yet but no big API changes are expected.

There's also [Getting Started](https://github.com/hoedown/hoedown/wiki/Getting-Started) which is a short (and complete) intro to the main v3 API. Full docs are in the works.

**Comment by chobie** [comment]
@devinus @jmendeth yea, I saw that. but that migration guid only explains about mapping.
It was little bit difficult work as our migration aims hoedown v3 api from sundown.
this is good news. almost test cases passed on my machine with latest hoedown master branch.

The remaining problem is we don't have good reference for developing hoedown binding.

Well, what was good point about sundown. It has ruby binding which made from library author
(additionally, it uses Github production environment.)
Binding developer could reference that implementation. it's very easy to understand.
Especially, redcarpet classes helped me when considering API.

For example. `hoedown_html_renderer_new` has `nesting_level` parameter and it little bit different form sundown api. I have to check hoedown commit logs and have to think why refactor this.
It's okay if I have enough time. but actually, I have little pockets of time.

for now, I'd like to keep current status

**Comment by chobie** [comment]
@kjdev created hoedown extension. so I'd like to aim to keep redcarpet compatibility.

https://github.com/kjdev/php-ext-hoedown
